/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const IndexCheckerStatus = IDL.Record({
  'url' : IDL.Text,
  'indexabilityIssues' : IDL.Vec(IDL.Text),
  'noindexTagPresent' : IDL.Bool,
  'robotsBlocked' : IDL.Bool,
  'lastChecked' : Time,
  'isIndexed' : IDL.Bool,
});
export const KeywordAnalysisPosition = IDL.Record({
  'domain' : IDL.Text,
  'position' : IDL.Int,
});
export const KeywordAnalysis = IDL.Record({
  'keywordDifficulty' : IDL.Int,
  'top10Positions' : IDL.Vec(KeywordAnalysisPosition),
  'searchVolumeEstimate' : IDL.Int,
  'competitorDomain' : IDL.Text,
  'keyword' : IDL.Text,
  'analysisTimestamp' : Time,
});
export const OptimizationTip = IDL.Record({
  'title' : IDL.Text,
  'impactLevel' : IDL.Text,
  'description' : IDL.Text,
  'implemented' : IDL.Bool,
  'category' : IDL.Text,
});
export const TechnicalSEO = IDL.Record({
  'mobileFriendly' : IDL.Bool,
  'pageSpeedScore' : IDL.Int,
  'sitemapPresent' : IDL.Bool,
  'sslEnabled' : IDL.Bool,
  'structuredDataPresent' : IDL.Bool,
  'robotsTxtPresent' : IDL.Bool,
  'canonicalTagPresent' : IDL.Bool,
});
export const OffPageSEO = IDL.Record({
  'socialSignalsCount' : IDL.Int,
  'domainAuthorityScore' : IDL.Int,
  'backlinkCountEstimate' : IDL.Int,
});
export const NonTechnicalSEO = IDL.Record({
  'contentLengthWords' : IDL.Int,
  'readabilityScore' : IDL.Int,
  'keywordUsageScore' : IDL.Int,
  'contentQualityScore' : IDL.Int,
});
export const OnPageSEO = IDL.Record({
  'metaDescriptionPresent' : IDL.Bool,
  'metaDescriptionQuality' : IDL.Int,
  'h3Count' : IDL.Int,
  'h1Count' : IDL.Int,
  'titleQualityScore' : IDL.Int,
  'internalLinkCount' : IDL.Int,
  'titleTagPresent' : IDL.Bool,
  'imageAltTagCoverage' : IDL.Float64,
  'h2Count' : IDL.Int,
  'keywordDensityScore' : IDL.Float64,
});
export const SEOAuditResult = IDL.Record({
  'url' : IDL.Text,
  'technical' : TechnicalSEO,
  'auditTimestamp' : Time,
  'offPage' : OffPageSEO,
  'nonTechnical' : NonTechnicalSEO,
  'onPage' : OnPageSEO,
});
export const WebsiteStatus = IDL.Record({
  'url' : IDL.Text,
  'isOnline' : IDL.Bool,
  'httpStatusCode' : IDL.Int,
  'responseTimeMs' : IDL.Int,
  'uptimePercentage' : IDL.Float64,
  'lastChecked' : Time,
});
export const DashboardSummary = IDL.Record({
  'performanceScore' : IDL.Int,
  'totalSitesAnalyzed' : IDL.Nat,
  'totalIssuesFound' : IDL.Nat,
  'lastUpdated' : Time,
  'seoScore' : IDL.Int,
  'overallHealthScore' : IDL.Int,
});

export const idlService = IDL.Service({
  'addIndexCheckerStatus' : IDL.Func([IndexCheckerStatus], [], []),
  'addKeywordAnalysis' : IDL.Func([IDL.Text, KeywordAnalysis], [], []),
  'addOptimizationTip' : IDL.Func([IDL.Text, OptimizationTip], [], []),
  'addSEOAdit' : IDL.Func([SEOAuditResult], [], []),
  'addWebsiteStatus' : IDL.Func([WebsiteStatus], [], []),
  'getAllSEOAudits' : IDL.Func([], [IDL.Vec(SEOAuditResult)], ['query']),
  'getAllWebsiteStatuses' : IDL.Func([], [IDL.Vec(WebsiteStatus)], ['query']),
  'getDashboardSummary' : IDL.Func([], [IDL.Opt(DashboardSummary)], ['query']),
  'getIndexCheckerStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IndexCheckerStatus)],
      ['query'],
    ),
  'getKeywordAnalysis' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(KeywordAnalysis)],
      ['query'],
    ),
  'getOptimizationTips' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OptimizationTip)],
      ['query'],
    ),
  'getSEOAdit' : IDL.Func([IDL.Text], [IDL.Opt(SEOAuditResult)], ['query']),
  'getWebsiteStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WebsiteStatus)],
      ['query'],
    ),
  'updateDashboardSummary' : IDL.Func([DashboardSummary], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const IndexCheckerStatus = IDL.Record({
    'url' : IDL.Text,
    'indexabilityIssues' : IDL.Vec(IDL.Text),
    'noindexTagPresent' : IDL.Bool,
    'robotsBlocked' : IDL.Bool,
    'lastChecked' : Time,
    'isIndexed' : IDL.Bool,
  });
  const KeywordAnalysisPosition = IDL.Record({
    'domain' : IDL.Text,
    'position' : IDL.Int,
  });
  const KeywordAnalysis = IDL.Record({
    'keywordDifficulty' : IDL.Int,
    'top10Positions' : IDL.Vec(KeywordAnalysisPosition),
    'searchVolumeEstimate' : IDL.Int,
    'competitorDomain' : IDL.Text,
    'keyword' : IDL.Text,
    'analysisTimestamp' : Time,
  });
  const OptimizationTip = IDL.Record({
    'title' : IDL.Text,
    'impactLevel' : IDL.Text,
    'description' : IDL.Text,
    'implemented' : IDL.Bool,
    'category' : IDL.Text,
  });
  const TechnicalSEO = IDL.Record({
    'mobileFriendly' : IDL.Bool,
    'pageSpeedScore' : IDL.Int,
    'sitemapPresent' : IDL.Bool,
    'sslEnabled' : IDL.Bool,
    'structuredDataPresent' : IDL.Bool,
    'robotsTxtPresent' : IDL.Bool,
    'canonicalTagPresent' : IDL.Bool,
  });
  const OffPageSEO = IDL.Record({
    'socialSignalsCount' : IDL.Int,
    'domainAuthorityScore' : IDL.Int,
    'backlinkCountEstimate' : IDL.Int,
  });
  const NonTechnicalSEO = IDL.Record({
    'contentLengthWords' : IDL.Int,
    'readabilityScore' : IDL.Int,
    'keywordUsageScore' : IDL.Int,
    'contentQualityScore' : IDL.Int,
  });
  const OnPageSEO = IDL.Record({
    'metaDescriptionPresent' : IDL.Bool,
    'metaDescriptionQuality' : IDL.Int,
    'h3Count' : IDL.Int,
    'h1Count' : IDL.Int,
    'titleQualityScore' : IDL.Int,
    'internalLinkCount' : IDL.Int,
    'titleTagPresent' : IDL.Bool,
    'imageAltTagCoverage' : IDL.Float64,
    'h2Count' : IDL.Int,
    'keywordDensityScore' : IDL.Float64,
  });
  const SEOAuditResult = IDL.Record({
    'url' : IDL.Text,
    'technical' : TechnicalSEO,
    'auditTimestamp' : Time,
    'offPage' : OffPageSEO,
    'nonTechnical' : NonTechnicalSEO,
    'onPage' : OnPageSEO,
  });
  const WebsiteStatus = IDL.Record({
    'url' : IDL.Text,
    'isOnline' : IDL.Bool,
    'httpStatusCode' : IDL.Int,
    'responseTimeMs' : IDL.Int,
    'uptimePercentage' : IDL.Float64,
    'lastChecked' : Time,
  });
  const DashboardSummary = IDL.Record({
    'performanceScore' : IDL.Int,
    'totalSitesAnalyzed' : IDL.Nat,
    'totalIssuesFound' : IDL.Nat,
    'lastUpdated' : Time,
    'seoScore' : IDL.Int,
    'overallHealthScore' : IDL.Int,
  });
  
  return IDL.Service({
    'addIndexCheckerStatus' : IDL.Func([IndexCheckerStatus], [], []),
    'addKeywordAnalysis' : IDL.Func([IDL.Text, KeywordAnalysis], [], []),
    'addOptimizationTip' : IDL.Func([IDL.Text, OptimizationTip], [], []),
    'addSEOAdit' : IDL.Func([SEOAuditResult], [], []),
    'addWebsiteStatus' : IDL.Func([WebsiteStatus], [], []),
    'getAllSEOAudits' : IDL.Func([], [IDL.Vec(SEOAuditResult)], ['query']),
    'getAllWebsiteStatuses' : IDL.Func([], [IDL.Vec(WebsiteStatus)], ['query']),
    'getDashboardSummary' : IDL.Func(
        [],
        [IDL.Opt(DashboardSummary)],
        ['query'],
      ),
    'getIndexCheckerStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IndexCheckerStatus)],
        ['query'],
      ),
    'getKeywordAnalysis' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(KeywordAnalysis)],
        ['query'],
      ),
    'getOptimizationTips' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OptimizationTip)],
        ['query'],
      ),
    'getSEOAdit' : IDL.Func([IDL.Text], [IDL.Opt(SEOAuditResult)], ['query']),
    'getWebsiteStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WebsiteStatus)],
        ['query'],
      ),
    'updateDashboardSummary' : IDL.Func([DashboardSummary], [], []),
  });
};

export const init = ({ IDL }) => { return []; };