/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardSummary {
  'performanceScore' : bigint,
  'totalSitesAnalyzed' : bigint,
  'totalIssuesFound' : bigint,
  'lastUpdated' : Time,
  'seoScore' : bigint,
  'overallHealthScore' : bigint,
}
export interface IndexCheckerStatus {
  'url' : string,
  'indexabilityIssues' : Array<string>,
  'noindexTagPresent' : boolean,
  'robotsBlocked' : boolean,
  'lastChecked' : Time,
  'isIndexed' : boolean,
}
export interface KeywordAnalysis {
  'keywordDifficulty' : bigint,
  'top10Positions' : Array<KeywordAnalysisPosition>,
  'searchVolumeEstimate' : bigint,
  'competitorDomain' : string,
  'keyword' : string,
  'analysisTimestamp' : Time,
}
export interface KeywordAnalysisPosition {
  'domain' : string,
  'position' : bigint,
}
export interface NonTechnicalSEO {
  'contentLengthWords' : bigint,
  'readabilityScore' : bigint,
  'keywordUsageScore' : bigint,
  'contentQualityScore' : bigint,
}
export interface OffPageSEO {
  'socialSignalsCount' : bigint,
  'domainAuthorityScore' : bigint,
  'backlinkCountEstimate' : bigint,
}
export interface OnPageSEO {
  'metaDescriptionPresent' : boolean,
  'metaDescriptionQuality' : bigint,
  'h3Count' : bigint,
  'h1Count' : bigint,
  'titleQualityScore' : bigint,
  'internalLinkCount' : bigint,
  'titleTagPresent' : boolean,
  'imageAltTagCoverage' : number,
  'h2Count' : bigint,
  'keywordDensityScore' : number,
}
export interface OptimizationTip {
  'title' : string,
  'impactLevel' : string,
  'description' : string,
  'implemented' : boolean,
  'category' : string,
}
export interface SEOAuditResult {
  'url' : string,
  'technical' : TechnicalSEO,
  'auditTimestamp' : Time,
  'offPage' : OffPageSEO,
  'nonTechnical' : NonTechnicalSEO,
  'onPage' : OnPageSEO,
}
export interface TechnicalSEO {
  'mobileFriendly' : boolean,
  'pageSpeedScore' : bigint,
  'sitemapPresent' : boolean,
  'sslEnabled' : boolean,
  'structuredDataPresent' : boolean,
  'robotsTxtPresent' : boolean,
  'canonicalTagPresent' : boolean,
}
export type Time = bigint;
export interface WebsiteStatus {
  'url' : string,
  'isOnline' : boolean,
  'httpStatusCode' : bigint,
  'responseTimeMs' : bigint,
  'uptimePercentage' : number,
  'lastChecked' : Time,
}
export interface _SERVICE {
  'addIndexCheckerStatus' : ActorMethod<[IndexCheckerStatus], undefined>,
  'addKeywordAnalysis' : ActorMethod<[string, KeywordAnalysis], undefined>,
  'addOptimizationTip' : ActorMethod<[string, OptimizationTip], undefined>,
  'addSEOAdit' : ActorMethod<[SEOAuditResult], undefined>,
  'addWebsiteStatus' : ActorMethod<[WebsiteStatus], undefined>,
  'getAllSEOAudits' : ActorMethod<[], Array<SEOAuditResult>>,
  'getAllWebsiteStatuses' : ActorMethod<[], Array<WebsiteStatus>>,
  'getDashboardSummary' : ActorMethod<[], [] | [DashboardSummary]>,
  'getIndexCheckerStatus' : ActorMethod<[string], [] | [IndexCheckerStatus]>,
  'getKeywordAnalysis' : ActorMethod<[string], Array<KeywordAnalysis>>,
  'getOptimizationTips' : ActorMethod<[string], Array<OptimizationTip>>,
  'getSEOAdit' : ActorMethod<[string], [] | [SEOAuditResult]>,
  'getWebsiteStatus' : ActorMethod<[string], [] | [WebsiteStatus]>,
  'updateDashboardSummary' : ActorMethod<[DashboardSummary], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];