/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TechnicalSEO {
    mobileFriendly: boolean;
    pageSpeedScore: bigint;
    sitemapPresent: boolean;
    sslEnabled: boolean;
    structuredDataPresent: boolean;
    robotsTxtPresent: boolean;
    canonicalTagPresent: boolean;
}
export type Time = bigint;
export interface WebsiteStatus {
    url: string;
    isOnline: boolean;
    httpStatusCode: bigint;
    responseTimeMs: bigint;
    uptimePercentage: number;
    lastChecked: Time;
}
export interface SEOAuditResult {
    url: string;
    technical: TechnicalSEO;
    auditTimestamp: Time;
    offPage: OffPageSEO;
    nonTechnical: NonTechnicalSEO;
    onPage: OnPageSEO;
}
export interface OffPageSEO {
    socialSignalsCount: bigint;
    domainAuthorityScore: bigint;
    backlinkCountEstimate: bigint;
}
export interface KeywordAnalysis {
    keywordDifficulty: bigint;
    top10Positions: Array<KeywordAnalysisPosition>;
    searchVolumeEstimate: bigint;
    competitorDomain: string;
    keyword: string;
    analysisTimestamp: Time;
}
export interface NonTechnicalSEO {
    contentLengthWords: bigint;
    readabilityScore: bigint;
    keywordUsageScore: bigint;
    contentQualityScore: bigint;
}
export interface KeywordAnalysisPosition {
    domain: string;
    position: bigint;
}
export interface OptimizationTip {
    title: string;
    impactLevel: string;
    description: string;
    implemented: boolean;
    category: string;
}
export interface OnPageSEO {
    metaDescriptionPresent: boolean;
    metaDescriptionQuality: bigint;
    h3Count: bigint;
    h1Count: bigint;
    titleQualityScore: bigint;
    internalLinkCount: bigint;
    titleTagPresent: boolean;
    imageAltTagCoverage: number;
    h2Count: bigint;
    keywordDensityScore: number;
}
export interface IndexCheckerStatus {
    url: string;
    indexabilityIssues: Array<string>;
    noindexTagPresent: boolean;
    robotsBlocked: boolean;
    lastChecked: Time;
    isIndexed: boolean;
}
export interface DashboardSummary {
    performanceScore: bigint;
    totalSitesAnalyzed: bigint;
    totalIssuesFound: bigint;
    lastUpdated: Time;
    seoScore: bigint;
    overallHealthScore: bigint;
}
export interface backendInterface {
    addIndexCheckerStatus(status: IndexCheckerStatus): Promise<void>;
    addKeywordAnalysis(keyword: string, analysis: KeywordAnalysis): Promise<void>;
    addOptimizationTip(url: string, tip: OptimizationTip): Promise<void>;
    addSEOAdit(audit: SEOAuditResult): Promise<void>;
    addWebsiteStatus(status: WebsiteStatus): Promise<void>;
    getAllSEOAudits(): Promise<Array<SEOAuditResult>>;
    getAllWebsiteStatuses(): Promise<Array<WebsiteStatus>>;
    getDashboardSummary(): Promise<DashboardSummary | null>;
    getIndexCheckerStatus(url: string): Promise<IndexCheckerStatus | null>;
    getKeywordAnalysis(keyword: string): Promise<Array<KeywordAnalysis>>;
    getOptimizationTips(url: string): Promise<Array<OptimizationTip>>;
    getSEOAdit(url: string): Promise<SEOAuditResult | null>;
    getWebsiteStatus(url: string): Promise<WebsiteStatus | null>;
    updateDashboardSummary(summary: DashboardSummary): Promise<void>;
}
import type { DashboardSummary as _DashboardSummary, IndexCheckerStatus as _IndexCheckerStatus, SEOAuditResult as _SEOAuditResult, WebsiteStatus as _WebsiteStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addIndexCheckerStatus(arg0: IndexCheckerStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIndexCheckerStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIndexCheckerStatus(arg0);
            return result;
        }
    }
    async addKeywordAnalysis(arg0: string, arg1: KeywordAnalysis): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addKeywordAnalysis(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKeywordAnalysis(arg0, arg1);
            return result;
        }
    }
    async addOptimizationTip(arg0: string, arg1: OptimizationTip): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOptimizationTip(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOptimizationTip(arg0, arg1);
            return result;
        }
    }
    async addSEOAdit(arg0: SEOAuditResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSEOAdit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSEOAdit(arg0);
            return result;
        }
    }
    async addWebsiteStatus(arg0: WebsiteStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWebsiteStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWebsiteStatus(arg0);
            return result;
        }
    }
    async getAllSEOAudits(): Promise<Array<SEOAuditResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSEOAudits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSEOAudits();
            return result;
        }
    }
    async getAllWebsiteStatuses(): Promise<Array<WebsiteStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWebsiteStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWebsiteStatuses();
            return result;
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIndexCheckerStatus(arg0: string): Promise<IndexCheckerStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIndexCheckerStatus(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIndexCheckerStatus(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKeywordAnalysis(arg0: string): Promise<Array<KeywordAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKeywordAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKeywordAnalysis(arg0);
            return result;
        }
    }
    async getOptimizationTips(arg0: string): Promise<Array<OptimizationTip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOptimizationTips(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOptimizationTips(arg0);
            return result;
        }
    }
    async getSEOAdit(arg0: string): Promise<SEOAuditResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSEOAdit(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSEOAdit(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebsiteStatus(arg0: string): Promise<WebsiteStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsiteStatus(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsiteStatus(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDashboardSummary(arg0: DashboardSummary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDashboardSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDashboardSummary(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DashboardSummary]): DashboardSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IndexCheckerStatus]): IndexCheckerStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SEOAuditResult]): SEOAuditResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WebsiteStatus]): WebsiteStatus | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
